#!/usr/bin/env python3

HMO_FILE = "Phylogenetic_Hierarchical_Orthogroups/N0.tsv"

f = open(HMO_FILE, 'r')

for line in f.readlines():
    fields = line.split('\t')
    hog = fields[0]
    og = fields[1]
    geneTreeParentClade = fields[2]
    identifiers = ""
    for i in range(3, len(fields)):
        blurbs = fields[i].split(',')
        for blurb in blurbs:
            pieces = blurb.strip().split(' ')
            gene = pieces[0].strip()
            if (len(gene)>0):
                identifiers = identifiers + '\t' + gene
    print(hog+"\t"+og+"\t"+geneTreeParentClade+identifiers)
